version: '2'
services:
  server:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - sinatra:upstream
    depends_on:
      - sinatra
  sinatra:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: bundle exec ruby myapp.rb
    ports:
      - "4567:4567"

