# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "activerecord"
gem "rake"
gem "sinatra-activerecord"
gem "sqlite3"
gem "selenium-webdriver"
gem "slack-ruby-client"

group :development do
  gem "pry"
  gem "pry-byebug"
end